import React, { createContext, useContext, useState, useCallback, useEffect, useMemo } from 'react';

/* ================================================================== */
/* Application (portal) strings — centralized dictionary.              */
/* The `hi` map only needs overrides: missing keys fall back to English */
/* at module load, so a label can never render as `undefined`.          */
/* Technical values (GSTIN, MRP, IDs, barcode data) are never           */
/* translated — only surrounding UI labels live here.                   */
/* ================================================================== */

const appStrings = {
  en: {
    /* portal identity + shell */
    portalInspector: 'Inspector Portal',
    portalGov: 'Govt. Officer Portal',
    brandName: 'Legal Metrology',
    brandSub: 'Compliance System · Government of India',
    searchInspector: 'Search inspections, products, retailers…',
    searchGov: 'Search inspections, manufacturers, cases…',
    globalSearch: 'Global search',
    myProfile: 'My Profile',
    signOut: 'Sign out',
    notifications: 'Notifications',

    /* navigation */
    navDashboard: 'Dashboard',
    navNewInspection: 'New Inspection',
    navInspections: 'Inspections',
    navReports: 'Reports',
    navManufacturers: 'Manufacturers',
    navViolations: 'Violations',
    navCases: 'Cases & Enforcement',
    navAnalytics: 'Analytics',
    navRepository: 'Repository',
    navProfile: 'My Profile',
    navSettings: 'Settings',

    /* common actions */
    back: 'Back',
    continue: 'Continue',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    remove: 'Remove',
    retry: 'Retry',
    clearSearch: 'Clear search',
    viewDetails: 'View details',
    downloadPdf: 'Download PDF',
    downloadEditable: 'Editable Report',
    submit: 'Submit Inspection',
    loading: 'Loading…',

    /* shared tables + empty states */
    searchPlaceholder: 'Search ID, product, establishment, manufacturer, inspector…',
    searchInspections: 'Search inspections',
    noInspections: 'No inspections found',
    noResultsHint: 'Adjust the search term or status filter to see more results.',
    tabAll: 'All',
    tabCompliant: 'Compliant',
    tabNonCompliant: 'Non-Compliant',
    tabPending: 'Pending',
    colId: 'Inspection ID',
    colDate: 'Date',
    colProduct: 'Product',
    colManufacturer: 'Manufacturer',
    colEstablishment: 'Establishment',
    colInspector: 'Inspector',
    colStatus: 'Status',
    colActions: 'Actions',
    prevPage: 'Previous page',
    nextPage: 'Next page',
    pageInfo: 'Page {page} of {total}',

    /* page titles */
    titleDashboard: 'Dashboard',
    titleHistory: 'Inspection History',
    subtitleHistory: 'View and manage past inspections.',
    titleNewInspection: 'New Inspection',
    subtitleNewInspection: 'Capture → Extract → Verify → Evidence → Report',
    titleReports: 'Reports & Analytics',
    titleManufacturers: 'Manufacturer Management',
    titleSettings: 'Settings',

    /* dashboard */
    welcomeBack: 'Welcome back — conduct inspections, document evidence, submit results.',
    statInspections: 'Inspections',
    statAllRecords: 'All records',
    statCompliant: 'Compliant Products',
    statNonCompliant: 'Non-Compliant Products',
    statPending: 'Pending Reports',

    /* wizard */
    stepDetails: 'Details',
    stepCapture: 'Capture',
    stepExtraction: 'Extraction',
    stepCompliance: 'Compliance',
    stepEvidence: 'Evidence',
    stepReport: 'Report',
    startInspection: 'Start Inspection',

    /* government portal pages */
    titleGovDashboard: 'Department Command Center',
    subtitleGovDashboard: 'Monitor → Investigate → Manage → Enforce. All figures reflect filed department records.',
    titleMonitoring: 'Inspection Monitoring',
    subtitleMonitoring: 'All inspections across the department — view-only, with full evidence access.',
    titleViolations: 'Violation Register',
    subtitleViolations: 'Violations derived live from filed inspection findings.',
    titleGovReports: 'Department Reports',
    subtitleGovReports: 'Filed inspection reports across the department.',
    titleRepository: 'Repository',
    subtitleRepository: 'Global search across inspections, manufacturers, products and violations.',
    titleAnalytics: 'Department Analytics',
    subtitleAnalytics: 'Compliance and violation analytics derived from filed records.',
    titleManufacturerLookup: 'Manufacturer Lookup',
    subtitleManufacturerLookup: 'Read-only reference. Official records are managed by the department.',

    /* government stats */
    statTotalInspections: 'Total Inspections',
    hintDepartmentWide: 'Department-wide',
    statComplianceRate: 'Compliance Rate',
    hintComplianceRate: 'Compliant ÷ total',
    statDeclarationViolations: 'Declaration Violations',
    hintAcrossInspections: 'Across all inspections',
    statOpenCases: 'Open Cases',
    hintAwaitingDecision: 'Awaiting officer decision',
    statManufacturers: 'Manufacturers',
    hintRegistered: 'Registered records',
    statHighRisk: 'High-Risk Manufacturers',
    hintHighRisk: 'HIGH or CRITICAL classification',
    statActionsRecorded: 'Actions Recorded',
    hintEnforcement: 'Enforcement decisions',
    statActiveInspectors: 'Active Inspectors',
    hintFiledInspections: 'With filed inspections',
    cardViolationsByCategory: 'Violations by Category',
    cardComplianceTrend: 'Compliance Trend — from department records',
    emptyNoViolations: 'No violations recorded.',
    emptyTrendPending: 'No inspections recorded yet — trends appear as inspectors file reports.',

    /* wizard capture/extraction */
    captureTitle: 'Capture Product',
    captureIntro: 'Upload the product label image to run the analysis pipeline.',
    tabUpload: 'Upload Image',
    tabBarcode: 'Scan Barcode',
    chooseImage: 'Choose Product Image',
    replaceImage: 'Replace Image',
    noImageSelected: 'No image selected',
    barcodeUnavailable: 'Camera barcode scanning is not available in this build. Enter the barcode later on the Extraction step, or upload a clear photo of the label — the barcode printed on it is read as part of the analysis.',
    capturedImage: 'Captured Image',
    imageReady: 'Image ready for analysis. Continue to run the existing extraction pipeline — every required declaration is editable afterwards.',
    noImageYet: 'No image uploaded yet.',
    changeImage: 'Change Image',
    extractionTitle: 'Extracted Product Information',
    extractionIntro: 'Review and confirm the details detected by automated extraction. Edits are marked as inspector-verified.',
    extractedDetails: 'Extracted Details',
    chipAutomated: 'Automated',
    notDetected: 'Not detected',
    notDetectedManual: 'Not detected — enter manually',
    enterValue: 'Enter value',
    verified: 'Verified',
    verifiedEdited: 'Verified (edited)',
    lowConfidence: 'Low confidence',
    manualEntryRequired: 'Manual entry required',
    analysisFailed: 'Analysis could not be completed. Try again.',
    imageUnreadable: 'That image could not be read. Try a JPG or PNG photo of the label.',
    retryAnalysis: 'Retry analysis',
    backToCapture: 'Back to capture',
    enterManually: 'Enter details manually',
    ocrServiceUnreachable: 'The analysis service is not reachable. Start it (cd ocr-service && uvicorn app:app --port 8100), retry, or enter the details manually.',
    searchMfrPlaceholder: 'Search name, trade name, GSTIN, license number…',
    searchMfrAria: 'Search manufacturers',
    mfrNoMatches: 'No manufacturers match',
    mfrNothingFound: 'Nothing found for',

    /* wizard compliance/evidence/report */
    complianceTitle: 'Compliance Verification',
    complianceIntroPrefix: 'Rule-based evaluation against the Legal Metrology (Packaged Commodities) Rules, 2011 —',
    complianceIntroSuffix: 'checks passed. Automated findings are advisory; you confirm the final verdict.',
    colCheck: 'Check',
    colRuleRef: 'Rule Reference',
    colRemarks: 'Remarks',
    noFindings: 'No findings recorded',
    noFindingsSub: 'Go back and complete the image analysis to generate rule-based findings.',
    evidenceTitle: 'Evidence & Review',
    evidenceIntro: 'Attach photographs, review highlighted violation regions and confirm the findings.',
    addEvidence: 'Add Evidence Photos',
    noEvidenceYet: 'No evidence attached yet.',
    notesLabel: 'Inspector Notes',
    notesPlaceholder: 'Record observations for the official record…',
    confirmText: 'I confirm the extracted information has been verified by me and the recorded evidence is accurate.',
    confirmError: 'Please confirm before continuing.',
    reportCardTitle: 'Inspection Report',
    complianceResult: 'Compliance Result',

    /* manufacturer pages */
    recordDetails: 'Record Details (read-only)',
    riskProfile: 'Risk Profile (explainable)',
    inspectionHistoryCount: 'Inspection History',
    noInspectionsRecorded: 'No inspections recorded',
    mfrNotInspected: 'This manufacturer has not been inspected yet.',
    registeredAddress: 'Registered address',
    license: 'License',
    recordSource: 'Record source',
    derivedFromInspection: 'Derived from inspection data (provisional)',
    departmentMaintained: 'Department-maintained',
    notProvided: 'Not provided',
    inspectionsRecorded: 'Inspections recorded',
    declarationViolations: 'Declaration violations',
    mfrNoRecordsYet: 'No manufacturer records yet',
    mfrNoRecordsSub: 'Records appear here automatically as inspections reference manufacturers. Submit an inspection with manufacturer details to begin building the registry.',

    /* profile */
    profileTitle: 'My Profile',
    profileEdit: 'Edit Profile',
    profileEditPending: 'Profile editing arrives with the backend phase — records are read-only in this demo.',
    profileEmployeeId: 'Employee ID',
    profileEmail: 'Email',
    profilePhone: 'Phone',
    profileDepartment: 'Department',
    profileDesignation: 'Designation',
    profileRegion: 'Region',
    profileJoined: 'Date of Joining',
    profileSignature: 'Digital Signature',
    profileSigPending: 'Not registered',
    notOnFile: 'Not on file',
    home: 'Home',
    analyzing: 'Analyzing product label',
    analysisUpload: 'Uploading image',
    analysisProcess: 'Processing image',
    analysisOcr: 'Reading declarations (OCR)',
    analysisCompliance: 'Checking compliance',
    analysisPrepare: 'Preparing results',

    /* inspection detail (shared) */
    inspectionNotFound: 'Inspection not found',
    noInspectionForId: 'No inspection record found for ID',
    backToHistory: 'Back to history',
    backToMonitoring: 'Back to monitoring',
    inspectionMonitoring: 'Inspection Monitoring',
    viewOnly: 'view-only',
    btnEditable: 'Editable',
    cardEvidence: 'Evidence',
    noEvidenceAttached: 'No evidence attached.',
    automatedExtractionTitle: 'Automated Extraction — what was detected',
    automatedExtractionIntro: 'Values below were produced by automated extraction. Compliance verdicts come from the rule engine; the inspector verified the final result.',
    ruleFindingsTitle: 'Rule Findings — whether it satisfies the rule',
    ruleFindingsIntro: 'Produced by the rule-based compliance engine (LM (PC) Rules 2011). Inspector-verified at submission.',
    colDeclaration: 'Declaration',
    colExtractedValue: 'Extracted Value',
    colConfidence: 'Confidence',
    notFoundBadge: '✕ Not found',
    dimPresence: 'Presence',
    dimCorrectness: 'Value',
    dimPlacement: 'Placement',
    dimReadability: 'Readability',
    dimFontSize: 'Font size',
    colViolationRule: 'Violation · Rule',

    /* gov manufacturer management */
    govMfrTitle: 'Manufacturer Management',
    govMfrSubtitle: 'Official manufacturer records. Inspectors have read-only access to this data.',
    addManufacturer: 'Add Manufacturer',
    loadingManufacturers: 'Loading manufacturers…',
    mfrNoRecordsCreate: 'No manufacturer records yet',
    mfrCreateFirst: 'Create the first official record.',
    colMfrName: 'Manufacturer',
    colGstin: 'GSTIN',
    colLicense: 'License',
    colInspections: 'Inspections',
    colViolations: 'Violations',
    colRisk: 'Risk',
    addMfrTitle: 'Add Manufacturer Record',
    legalNameLabel: 'Legal name',
    legalNamePlaceholder: 'M/s Example Foods Pvt Ltd',
    tradeNameLabel: 'Trade name',
    tradeNamePlaceholder: 'Example Foods',
    gstinLabel: 'GSTIN',
    licenseNumberLabel: 'License number',
    contactLabel: 'Contact',
    registeredAddressLabel: 'Registered address',
    productCategoriesLabel: 'Product categories',
    productCategoriesPlaceholder: 'Comma-separated, e.g. Edible Oils, Snacks',
    createRecord: 'Create Record',
    legalNameRequired: 'Legal name is required',
    gstinInvalid: 'GSTIN must match the 15-character format (e.g. 06AACCS1234K1Z5)',
    addressRequired: 'Registered address is required',
    officialRecord: 'Official Record',
    tradeName: 'Trade name',
    licenseLabel: 'License',
    complianceSnapshot: 'Compliance Snapshot',
    riskProfileExplainable: 'Risk Profile (explainable)',
    riskClassifiedPrefix: 'Classified',
    riskFromHistory: 'from the recorded history above —',
    violationsAcross: 'violation(s) across',
    inspectionsLinked: 'inspection(s) linked to this manufacturer.',
    failedChecksAcross: 'failed declaration check(s) across those inspections.',
    riskFootnote: 'Classification is rule-based on the factors above — transparent, never an unexplained AI score. License actions are taken from the Cases & Enforcement workflow only.',
    manufacturerNotFound: 'Manufacturer not found',
    backToManagement: 'Back to management',
  },

  hi: {
    portalInspector: 'निरीक्षक पोर्टल',
    portalGov: 'अधिकारी पोर्टल',
    brandName: 'वैधानिक मापन',
    brandSub: 'अनुपालन प्रणाली · भारत सरकार',
    searchInspector: 'निरीक्षण, उत्पाद, फ़ुटकर विक्रेता खोजें…',
    searchGov: 'निरीक्षण, उत्पादक, मामले खोजें…',
    globalSearch: 'वैश्विक खोज',
    myProfile: 'मेरी प्रोफ़ाइल',
    signOut: 'साइन आउट',
    notifications: 'सूचनाएँ',

    navDashboard: 'डैशबोर्ड',
    navNewInspection: 'नया निरीक्षण',
    navInspections: 'निरीक्षण',
    navReports: 'रिपोर्ट',
    navManufacturers: 'उत्पादक',
    navViolations: 'उल्लंघन',
    navCases: 'मामले एवं प्रवर्तन',
    navAnalytics: 'विश्लेषण',
    navRepository: 'भंडार',
    navProfile: 'मेरी प्रोफ़ाइल',
    navSettings: 'सेटिंग्स',

    back: 'वापस',
    continue: 'आगे बढ़ें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    edit: 'संपादित करें',
    remove: 'हटाएँ',
    retry: 'पुनः प्रयास',
    clearSearch: 'खोज साफ़ करें',
    viewDetails: 'विवरण देखें',
    downloadPdf: 'PDF डाउनलोड करें',
    downloadEditable: 'संपादन योग्य रिपोर्ट',
    submit: 'निरीक्षण जमा करें',
    loading: 'लोड हो रहा है…',

    /* shared tables + empty states */
    searchPlaceholder: 'आईडी, उत्पाद, प्रतिष्ठान, उत्पादक, निरीक्षक खोजें…',
    searchInspections: 'निरीक्षण खोजें',
    noInspections: 'कोई निरीक्षण नहीं मिला',
    noResultsHint: 'अधिक परिणाम देखने के लिए खोज शब्द या स्थिति फ़िल्टर बदलें।',
    tabAll: 'सभी',
    tabCompliant: 'अनुपालनशील',
    tabNonCompliant: 'गैर-अनुपालनशील',
    tabPending: 'लंबित',
    colId: 'निरीक्षण आईडी',
    colDate: 'दिनांक',
    colProduct: 'उत्पाद',
    colManufacturer: 'उत्पादक',
    colEstablishment: 'प्रतिष्ठान',
    colInspector: 'निरीक्षक',
    colStatus: 'स्थिति',
    colActions: 'क्रियाएँ',
    prevPage: 'पिछला पृष्ठ',
    nextPage: 'अगला पृष्ठ',
    pageInfo: 'पृष्ठ {page} / {total}',

    titleDashboard: 'डैशबोर्ड',
    titleHistory: 'निरीक्षण इतिहास',
    subtitleHistory: 'पिछले निरीक्षण देखें और प्रबंधित करें।',
    titleNewInspection: 'नया निरीक्षण',
    subtitleNewInspection: 'कैप्चर → निष्कर्षण → सत्यापन → साक्ष्य → रिपोर्ट',
    titleReports: 'रिपोर्ट एवं विश्लेषण',
    titleManufacturers: 'उत्पादक प्रबंधन',
    titleSettings: 'सेटिंग्स',

    /* dashboard */
    welcomeBack: 'आपका स्वागत है — निरीक्षण करें, साक्ष्य दर्ज करें, परिणाम जमा करें।',
    statInspections: 'निरीक्षण',
    statAllRecords: 'सभी रिकॉर्ड',
    statCompliant: 'अनुपालनशील उत्पाद',
    statNonCompliant: 'गैर-अनुपालनशील उत्पाद',
    statPending: 'लंबित रिपोर्ट',

    stepDetails: 'विवरण',
    stepCapture: 'कैप्चर',
    stepExtraction: 'निष्कर्षण',
    stepCompliance: 'अनुपालन',
    stepEvidence: 'साक्ष्य',
    stepReport: 'रिपोर्ट',
    startInspection: 'निरीक्षण प्रारंभ करें',

    titleGovDashboard: 'विभाग कमांड केंद्र',
    subtitleGovDashboard: 'निगरानी → जाँच → प्रबंधन → प्रवर्तन। सभी आँकड़े दर्ज विभागीय रिकॉर्ड से हैं।',
    titleMonitoring: 'निरीक्षण निगरानी',
    subtitleMonitoring: 'विभाग भर के सभी निरीक्षण — केवल देखें, पूर्ण साक्ष्य उपलब्ध।',
    titleViolations: 'उल्लंघन रजिस्टर',
    subtitleViolations: 'दर्ज निरीक्षण निष्कर्षों से लाइव उल्लंघन।',
    titleGovReports: 'विभागीय रिपोर्ट',
    subtitleGovReports: 'विभाग भर में दर्ज निरीक्षण रिपोर्ट।',
    titleRepository: 'भंडार',
    subtitleRepository: 'निरीक्षण, उत्पादक, उत्पाद और उल्लंघनों की वैश्विक खोज।',
    titleAnalytics: 'विभागीय विश्लेषण',
    subtitleAnalytics: 'दर्ज रिकॉर्ड से अनुपालन एवं उल्लंघन विश्लेषण।',
    titleManufacturerLookup: 'उत्पादक खोज',
    subtitleManufacturerLookup: 'केवल-पठन संदर्भ। आधिकारिक रिकॉर्ड विभाग द्वारा प्रबंधित।',

    statTotalInspections: 'कुल निरीक्षण',
    hintDepartmentWide: 'विभाग-व्यापी',
    statComplianceRate: 'अनुपालन दर',
    hintComplianceRate: 'अनुपालनशील ÷ कुल',
    statDeclarationViolations: 'घोषणा उल्लंघन',
    hintAcrossInspections: 'सभी निरीक्षणों में',
    statOpenCases: 'खुले मामले',
    hintAwaitingDecision: 'अधिकारी निर्णय प्रतीक्षित',
    statManufacturers: 'उत्पादक',
    hintRegistered: 'पंजीकृत रिकॉर्ड',
    statHighRisk: 'उच्च-जोखिम उत्पादक',
    hintHighRisk: 'उच्च या अत्यधिक वर्गीकरण',
    statActionsRecorded: 'दर्ज कार्रवाइयाँ',
    hintEnforcement: 'प्रवर्तन निर्णय',
    statActiveInspectors: 'सक्रिय निरीक्षक',
    hintFiledInspections: 'निरीक्षण दर्ज किए',
    cardViolationsByCategory: 'श्रेणी अनुसार उल्लंघन',
    cardComplianceTrend: 'अनुपालन प्रवृत्ति — विभागीय रिकॉर्ड से',
    emptyNoViolations: 'कोई उल्लंघन दर्ज नहीं।',
    emptyTrendPending: 'अभी कोई निरीक्षण दर्ज नहीं — निरीक्षक रिपोर्ट दर्ज करते ही प्रवृत्तियाँ दिखेंगी।',

    captureTitle: 'उत्पाद कैप्चर करें',
    captureIntro: 'विश्लेषण पाइपलाइन चलाने हेतु उत्पाद लेबल छवि अपलोड करें।',
    tabUpload: 'छवि अपलोड करें',
    tabBarcode: 'बारकोड स्कैन करें',
    chooseImage: 'उत्पाद छवि चुनें',
    replaceImage: 'छवि बदलें',
    noImageSelected: 'कोई छवि चयनित नहीं',
    barcodeUnavailable: 'इस बिल्ड में कैमरा बारकोड स्कैनिंग उपलब्ध नहीं है। बारकोड बाद में निष्कर्षण चरण पर दर्ज करें, या लेबल की स्पष्ट फ़ोटो अपलोड करें — उस पर छपा बारकोड विश्लेषण के भाग के रूप में पढ़ा जाता है।',
    capturedImage: 'कैप्चर की गई छवि',
    imageReady: 'विश्लेषण हेतु छवि तैयार। मौजूदा निष्कर्षण पाइपलाइन चलाने के लिए आगे बढ़ें — हर आवश्यक घोषणा बाद में संपादन योग्य है।',
    noImageYet: 'अभी कोई छवि अपलोड नहीं हुई।',
    changeImage: 'छवि बदलें',
    extractionTitle: 'निष्कर्षित उत्पाद जानकारी',
    extractionIntro: 'स्वचालित निष्कर्षण से प्राप्त विवरण की समीक्षा करें। संपादन निरीक्षक-सत्यापित चिह्नित होंगे।',
    extractedDetails: 'निष्कर्षित विवरण',
    chipAutomated: 'स्वचालित',
    notDetected: 'पता नहीं चला',
    notDetectedManual: 'पता नहीं चला — स्वयं भरें',
    enterValue: 'मान दर्ज करें',
    verified: 'सत्यापित',
    verifiedEdited: 'सत्यापित (संपादित)',
    lowConfidence: 'कम विश्वास',
    manualEntryRequired: 'मैनुअल प्रविष्टि आवश्यक',
    analysisFailed: 'विश्लेषण पूर्ण नहीं हो सका। पुनः प्रयास करें।',
    imageUnreadable: 'वह छवि पढ़ी नहीं जा सकी। लेबल की JPG या PNG फ़ोटो आज़माएँ।',
    retryAnalysis: 'विश्लेषण पुनः प्रयास',
    backToCapture: 'कैप्चर पर वापस',
    enterManually: 'विवरण स्वयं भरें',
    ocrServiceUnreachable: 'विश्लेषण सेवा उपलब्ध नहीं है। इसे चालू करें (cd ocr-service && uvicorn app:app --port 8100), पुनः प्रयास करें, या विवरण स्वयं भरें।',
    searchMfrPlaceholder: 'नाम, व्यापारिक नाम, GSTIN, लाइसेंस नंबर से खोजें…',
    searchMfrAria: 'उत्पादक खोजें',
    mfrNoMatches: 'कोई उत्पादक मेल नहीं खाता',
    mfrNothingFound: 'इसके लिए कुछ नहीं मिला:',

    complianceTitle: 'अनुपालन सत्यापन',
    complianceIntroPrefix: 'वैधानिक मापन (संवेदित माल) नियम, 2011 के विरुद्ध नियम-आधारित मूल्यांकन —',
    complianceIntroSuffix: 'जाँच पास। स्वचालित निष्कर्शन सलाहकारी हैं; अंतिम निर्णय आप पुष्टि करते हैं।',
    colCheck: 'जाँच',
    colRuleRef: 'नियम संदर्भ',
    colRemarks: 'टिप्पणी',
    noFindings: 'कोई निष्कर्ष दर्ज नहीं',
    noFindingsSub: 'नियम-आधारित निष्कर्श बनाने हेतु वापस जाकर छवि विश्लेषण पूर्ण करें।',
    evidenceTitle: 'साक्ष्य एवं समीक्षा',
    evidenceIntro: 'फ़ोटोग्राफ़ जोड़ें, उल्लंघन क्षेत्रों की समीक्षा करें और निष्कर्षों की पुष्टि करें।',
    addEvidence: 'साक्ष्य फ़ोटो जोड़ें',
    noEvidenceYet: 'अभी कोई साक्ष्य संलग्न नहीं।',
    notesLabel: 'निरीक्षक टिप्पणियाँ',
    notesPlaceholder: 'आधिकारिक रिकॉर्ड हेतु टिप्पणियाँ दर्ज करें…',
    confirmText: 'मैं पुष्टि करता हूँ कि निष्कर्षित जानकारी मेरे द्वारा सत्यापित है और दर्ज साक्ष्य सटीक है।',
    confirmError: 'जारी रखने से पहले पुष्टि करें।',
    reportCardTitle: 'निरीक्षण रिपोर्ट',
    complianceResult: 'अनुपालन परिणाम',

    recordDetails: 'रिकॉर्ड विवरण (केवल-पठन)',
    riskProfile: 'जोखिम प्रोफ़ाइल (व्याख्यात्मक)',
    inspectionHistoryCount: 'निरीक्षण इतिहास',
    noInspectionsRecorded: 'कोई निरीक्षण दर्ज नहीं',
    mfrNotInspected: 'इस उत्पादक का निरीक्षण अभी नहीं हुआ।',
    registeredAddress: 'पंजीकृत पता',
    license: 'लाइसेंस',
    recordSource: 'रिकॉर्ड स्रोत',
    derivedFromInspection: 'निरीक्षण डेटा से निर्मित (अस्थायी)',
    departmentMaintained: 'विभाग-अनुरक्षित',
    notProvided: 'उपलब्ध नहीं',
    inspectionsRecorded: 'दर्ज निरीक्षण',
    declarationViolations: 'घोषणा उल्लंघन',
    mfrNoRecordsYet: 'अभी कोई उत्पादक रिकॉर्ड नहीं',
    mfrNoRecordsSub: 'निरीक्षण उत्पादकों का उल्लेख करते ही रिकॉर्ड यहाँ स्वतः दिखाई देंगे। रजिस्टर बनाना शुरू करने हेतु उत्पादक विवरण सहित निरीक्षण जमा करें।',

    profileTitle: 'मेरी प्रोफ़ाइल',
    profileEdit: 'प्रोफ़ाइल संपादित करें',
    profileEditPending: 'प्रोफ़ाइल संपादन बैकएंड चरण के साथ आएगा — इस डेमो में रिकॉर्ड केवल-पठन हैं।',
    profileEmployeeId: 'कर्मचारी आईडी',
    profileEmail: 'ईमेल',
    profilePhone: 'फ़ोन',
    profileDepartment: 'विभाग',
    profileDesignation: 'पद',
    profileRegion: 'क्षेत्र',
    profileJoined: 'नामांकन तिथि',
    profileSignature: 'डिजिटल हस्ताक्षर',
    profileSigPending: 'पंजीकृत नहीं',
    notOnFile: 'रिकॉर्ड पर नहीं',
    home: 'होम',
    analyzing: 'उत्पाद लेबल विश्लेषित हो रहा है',
    analysisUpload: 'छवि अपलोड हो रही है',
    analysisProcess: 'छवि प्रोसेस हो रही है',
    analysisOcr: 'घोषणाएँ पढ़ी जा रही हैं (OCR)',
    analysisCompliance: 'अनुपालन जाँचा जा रहा है',
    analysisPrepare: 'परिणाम तैयार हो रहे हैं',

    /* inspection detail (shared) */
    inspectionNotFound: 'निरीक्षण नहीं मिला',
    noInspectionForId: 'इस आईडी का कोई निरीक्षण रिकॉर्ड नहीं मिला:',
    backToHistory: 'इतिहास पर वापस',
    backToMonitoring: 'निगरानी पर वापस',
    inspectionMonitoring: 'निरीक्षण निगरानी',
    viewOnly: 'केवल-देखें',
    btnEditable: 'संपादन योग्य',
    cardEvidence: 'साक्ष्य',
    noEvidenceAttached: 'कोई साक्ष्य संलग्न नहीं।',
    automatedExtractionTitle: 'स्वचालित निष्कर्षण — क्या पहचाना गया',
    automatedExtractionIntro: 'नीचे दिए मान स्वचालित निष्कर्षण से प्राप्त हैं। अनुपालन निर्णय नियम इंजन से आते हैं; अंतिम परिणाम निरीक्षक द्वारा सत्यापित है।',
    ruleFindingsTitle: 'नियम निष्कर्ष — क्या यह नियम को संतुष्ट करता है',
    ruleFindingsIntro: 'नियम-आधारित अनुपालन इंजन (LM (PC) नियम 2011) द्वारा निर्मित। जमा करते समय निरीक्षक-सत्यापित।',
    colDeclaration: 'घोषणा',
    colExtractedValue: 'निकाला गया मान',
    colConfidence: 'विश्वास',
    notFoundBadge: '✕ नहीं मिला',
    dimPresence: 'उपस्थिति',
    dimCorrectness: 'मान',
    dimPlacement: 'स्थान',
    dimReadability: 'पठनीयता',
    dimFontSize: 'फ़ॉन्ट आकार',
    colViolationRule: 'उल्लंघन · नियम',

    /* gov manufacturer management */
    govMfrTitle: 'उत्पादक प्रबंधन',
    govMfrSubtitle: 'आधिकारिक उत्पादक रिकॉर्ड। निरीक्षकों की पहुँच केवल-पठन है।',
    addManufacturer: 'उत्पादक जोड़ें',
    loadingManufacturers: 'उत्पादक लोड हो रहे हैं…',
    mfrNoRecordsCreate: 'अभी कोई उत्पादक रिकॉर्ड नहीं',
    mfrCreateFirst: 'पहला आधिकारिक रिकॉर्ड बनाएँ।',
    colMfrName: 'उत्पादक',
    colGstin: 'GSTIN',
    colLicense: 'लाइसेंस',
    colInspections: 'निरीक्षण',
    colViolations: 'उल्लंघन',
    colRisk: 'जोखिम',
    addMfrTitle: 'उत्पादक रिकॉर्ड जोड़ें',
    legalNameLabel: 'कानूनी नाम',
    legalNamePlaceholder: 'M/s Example Foods Pvt Ltd',
    tradeNameLabel: 'व्यापारिक नाम',
    tradeNamePlaceholder: 'Example Foods',
    gstinLabel: 'GSTIN',
    licenseNumberLabel: 'लाइसेंस नंबर',
    contactLabel: 'संपर्क',
    registeredAddressLabel: 'पंजीकृत पता',
    productCategoriesLabel: 'उत्पाद श्रेणियाँ',
    productCategoriesPlaceholder: 'अल्पविराम से, जैसे खाद्य तेल, स्नैक्स',
    createRecord: 'रिकॉर्ड बनाएँ',
    legalNameRequired: 'कानूनी नाम आवश्यक है',
    gstinInvalid: 'GSTIN 15-अक्षर प्रारूप से मेल खाना चाहिए (जैसे 06AACCS1234K1Z5)',
    addressRequired: 'पंजीकृत पता आवश्यक है',
    officialRecord: 'आधिकारिक रिकॉर्ड',
    tradeName: 'व्यापारिक नाम',
    licenseLabel: 'लाइसेंस',
    complianceSnapshot: 'अनुपालन स्नैपशॉट',
    riskProfileExplainable: 'जोखिम प्रोफ़ाइल (व्याख्यात्मक)',
    riskClassifiedPrefix: 'वर्गीकृत',
    riskFromHistory: 'ऊपर दर्ज इतिहास से —',
    violationsAcross: 'उल्लंघन, जिनमें',
    inspectionsLinked: 'निरीक्षण इस उत्पादक से जुड़े हैं।',
    failedChecksAcross: 'घोषणा जाँच उन निरीक्षणों में विफल रहीं।',
    riskFootnote: 'वर्गीकरण ऊपर दिए कारकों पर नियम-आधारित है — पारदर्शी, कभी भी अज्ञात AI स्कोर नहीं। लाइसेंस कार्रवाई केवल मामले एवं प्रवर्तन वर्कफ़्लो से होती है।',
    manufacturerNotFound: 'उत्पादक नहीं मिला',
    backToManagement: 'प्रबंधन पर वापस',
  },
};

// English fallback for any key the Hindi map does not override yet —
// guarantees no label ever renders as `undefined`.
const APP_TRANSLATIONS = {
  en: appStrings.en,
  hi: { ...appStrings.en, ...appStrings.hi },
};

const LANG_KEY = 'lmcs.language';

const translations = {
  en: {
    skipLink: 'Skip to main content',
    deptName: 'Department of Consumer Affairs',
    ministryName: 'Ministry of Consumer Affairs, Food & Public Distribution',
    countryName: 'Government of India',
    taglines: ['Ensure Fairness', 'Enable Compliance', 'Protect Consumers'],
    statusLabel: 'Portal Status: Operational',
    heroLine1: 'Legal Metrology',
    heroLine2: 'Compliance System',
    heroTagline: 'Scan · Verify · Enforce · Build a Fair Marketplace',
    heroDescription:
      'An AI-enabled solution to check compliance of Packaged Commodities under the Legal Metrology (Packaged Commodities) Rules, 2011.',
    features: [
      { line1: 'Scan', line2: 'Products' },
      { line1: 'Verify', line2: 'Declarations' },
      { line1: 'Detect', line2: 'Violations' },
      { line1: 'Generate', line2: 'Reports' },
    ],
    stats: [
      { value: '12,000+', label: 'Inspections Conducted' },
      { value: '98.2%', label: 'Detection Accuracy' },
      { value: '35s', label: 'Avg. Inspection Time' },
    ],
    trustItems: [
      { title: 'Fair Trade', sub: 'For Every Citizen' },
      { title: 'Accountable Markets', sub: 'For a Stronger Economy' },
      { title: 'Safe & Transparent', sub: 'For a Better Tomorrow' },
    ],
    showcaseAlt: 'Packaged Commodity Legal Metrology Compliance Inspection',
    jagoTitle: 'Jago Grahak Jago',
    jagoSub1: 'Aware Consumers',
    jagoSub2: 'Stronger India',
    cardTitle: 'Inspector Login',
    cardSubtitle: 'Access your account to continue',
    tabCredentials: 'Login with Credentials',
    tabSso: 'Login with Govt. SSO',
    labelUserId: 'User ID / Email',
    placeholderUserId: 'Enter your User ID or Email',
    labelPassword: 'Password',
    placeholderPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    loginBtn: 'Login',
    verifyingBtn: 'Verifying Credentials...',
    authenticatedBtn: 'Authenticated',
    successBanner: '✓ Verified Legal Metrology Inspector Session (Demo)',
    capsLockHint: 'Caps Lock is ON',
    demoHint: 'Demo: any credentials work — try "error123" as the password to preview the failure state',
    errors: {
      userIdRequired: 'Please enter your User ID or Email.',
      passwordRequired: 'Please enter your password.',
      passwordShort: 'Password must be at least 6 characters.',
      invalidCredentials: 'Invalid credentials. Check your User ID and password, then try again.',
    },
    ssoDesc: 'Authenticate via the Government of India Single Sign-On (MeriPehchaan / Jan Parichay).',
    ssoBtn: 'Proceed with Jan Parichay',
    aadhaarTitle: 'Login with Aadhaar',
    aadhaarSub: 'For Government Authorized Users',
    digilockerTitle: 'Login with DigiLocker',
    digilockerSub: 'Secure Access for Government Officers',
    newUser: 'New User?',
    contactAdmin: 'Contact your department administrator.',
    help: 'Help',
    privacy: 'Privacy Policy',
    terms: 'Terms of Use',
    atmanirbharLead: 'Contributing to',
    atmanirbhar: 'Atmanirbhar Bharat',
    atmanirbharTrail: 'through Responsible Markets',
    modal: {
      close: 'Close dialog',
      understood: 'Understood',
      forgotTitle: 'Password Recovery',
      forgotBody:
        'Password assistance: please contact your IT administrator or nodal officer for credential recovery. Demo mode — no email will be sent.',
      ssoTitle: 'MeriPehchaan / Jan Parichay SSO',
      ssoBody:
        'This triggers the National Single Sign-On gateway. In this frontend prototype the action is in demonstration mode.',
      aadhaarTitle: 'Aadhaar Auth Service',
      aadhaarBody:
        'This triggers the UIDAI Aadhaar OTP / Biometric authentication. In this frontend prototype the action is in demonstration mode.',
      digilockerTitle: 'DigiLocker SSO',
      digilockerBody:
        'This triggers the National DigiLocker OAuth 2.0 gateway. In this frontend prototype the action is in demonstration mode.',
    },
  },
  hi: {
    skipLink: 'मुख्य सामग्री पर जाएँ',
    deptName: 'उपभोक्ता मामले विभाग',
    ministryName: 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय',
    countryName: 'भारत सरकार',
    taglines: ['निष्पक्षता सुनिश्चित करें', 'अनुपालन सक्षम करें', 'उपभोक्ताओं की रक्षा करें'],
    statusLabel: 'पोर्टल स्थिति: संचालित',
    heroLine1: 'वैधानिक मापन',
    heroLine2: 'अनुपालन प्रणाली',
    heroTagline: 'स्कैन · सत्यापन · प्रवर्तन · निष्पक्ष बाज़ार बनाएँ',
    heroDescription:
      'वैधानिक मापन (संवेदित माल) नियम, 2011 के अंतर्गत संवेदित माल की अनुपालना जाँचने हेतु एआई-सक्षम समाधान।',
    features: [
      { line1: 'स्कैन', line2: 'उत्पाद' },
      { line1: 'सत्यापित', line2: 'घोषणाएँ' },
      { line1: 'पहचानें', line2: 'उल्लंघन' },
      { line1: 'तैयार करें', line2: 'रिपोर्ट' },
    ],
    stats: [
      { value: '12,000+', label: 'निरीक्षण किए गए' },
      { value: '98.2%', label: 'पहचान सटीकता' },
      { value: '35s', label: 'औसत निरीक्षण समय' },
    ],
    trustItems: [
      { title: 'निष्पक्ष व्यापार', sub: 'हर नागरिक के लिए' },
      { title: 'जवाबदेह बाज़ार', sub: 'मजबूत अर्थव्यवस्था के लिए' },
      { title: 'सुरक्षित व पारदर्शी', sub: 'बेहतर कल के लिए' },
    ],
    showcaseAlt: 'संवेदित माल वैधानिक मापन अनुपालन निरीक्षण',
    jagoTitle: 'जागो ग्राहक जागो',
    jagoSub1: 'जागरूक उपभोक्ता',
    jagoSub2: 'मजबूत भारत',
    cardTitle: 'निरीक्षक लॉगिन',
    cardSubtitle: 'जारी रखने के लिए अपने खाते में प्रवेश करें',
    tabCredentials: 'क्रेडेंशियल्स से लॉगिन',
    tabSso: 'सरकारी SSO से लॉगिन',
    labelUserId: 'उपयोगकर्ता आईडी / ईमेल',
    placeholderUserId: 'अपनी उपयोगकर्ता आईडी या ईमेल दर्ज करें',
    labelPassword: 'पासवर्ड',
    placeholderPassword: 'अपना पासवर्ड दर्ज करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    loginBtn: 'लॉगिन',
    verifyingBtn: 'क्रेडेंशियल्स सत्यापित हो रहे हैं...',
    authenticatedBtn: 'प्रमाणित',
    successBanner: '✓ वैधानिक मापन निरीक्षक सत्र सत्यापित (डेमो)',
    capsLockHint: 'कैप्स लॉक चालू है',
    demoHint: 'डेमो: कोई भी क्रेडेंशियल काम करते हैं — विफलता देखने के लिए पासवर्ड में "error123" आज़माएँ',
    errors: {
      userIdRequired: 'कृपया अपनी उपयोगकर्ता आईडी या ईमेल दर्ज करें।',
      passwordRequired: 'कृपया अपना पासवर्ड दर्ज करें।',
      passwordShort: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
      invalidCredentials: 'अमान्य क्रेडेंशियल्स। अपनी उपयोगकर्ता आईडी और पासवर्ड जाँचकर फिर से प्रयास करें।',
    },
    ssoDesc: 'भारत सरकार के सिंगल साइन-ऑन (मेरी पहचान / जन परिचय) के माध्यम से प्रमाणित करें।',
    ssoBtn: 'जन परिचय से आगे बढ़ें',
    aadhaarTitle: 'आधार से लॉगिन',
    aadhaarSub: 'सरकारी अधिकृत उपयोगकर्ताओं हेतु',
    digilockerTitle: 'डिजिलॉकर से लॉगिन',
    digilockerSub: 'सरकारी अधिकारियों हेतु सुरक्षित पहुँच',
    newUser: 'नए उपयोगकर्ता?',
    contactAdmin: 'अपने विभाग प्रशासक से संपर्क करें।',
    help: 'सहायता',
    privacy: 'गोपनीयता नीति',
    terms: 'उपयोग की शर्तें',
    atmanirbharLead: 'योगदान दे रहे हैं',
    atmanirbhar: 'आत्मनिर्भर भारत',
    atmanirbharTrail: 'जिम्मेदार बाज़ारों के माध्यम से',
    modal: {
      close: 'डायलॉग बंद करें',
      understood: 'समझ गया',
      forgotTitle: 'पासवर्ड पुनर्प्राप्ति',
      forgotBody:
        'पासवर्ड सहायता: क्रेडेंशियल पुनर्प्राप्ति हेतु कृपया अपने आईटी प्रशासक या नोडल अधिकारी से संपर्क करें। डेमो मोड — कोई ईमेल नहीं भेजा जाएगा।',
      ssoTitle: 'मेरी पहचान / जन परिचय SSO',
      ssoBody: 'यह राष्ट्रीय सिंगल साइन-ऑन गेटवे को ट्रिगर करता है। इस फ्रंटएंड प्रोटोटाइप में यह क्रिया डेमोन्स्ट्रेशन मोड में है।',
      aadhaarTitle: 'आधार प्रमाणीकरण सेवा',
      aadhaarBody: 'यह UIDAI आधार ओटीपी / बायोमेट्रिक प्रमाणीकरण को ट्रिगर करता है। इस फ्रंटएंड प्रोटोटाइप में यह क्रिया डेमोन्स्ट्रेशन मोड में है।',
      digilockerTitle: 'डिजिलॉकर SSO',
      digilockerBody: 'यह राष्ट्रीय डिजिलॉकर OAuth 2.0 गेटवे को ट्रिगर करता है। इस फ्रंटएंड प्रोटोटाइप में यह क्रिया डेमोन्स्ट्रेशन मोड में है।',
    },
  },
};

const LanguageContext = createContext(null);

const initialLang = () => {
  try {
    const saved = localStorage.getItem(LANG_KEY);
    return saved === 'hi' || saved === 'en' ? saved : 'en';
  } catch {
    return 'en';
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(initialLang);

  const setLang = useCallback((next) => {
    setLangState(next);
    try {
      localStorage.setItem(LANG_KEY, next);
    } catch {
      /* storage unavailable — language still applies for this session */
    }
  }, []);

  const toggleLang = useCallback(() => {
    setLang((current) => (current === 'en' ? 'hi' : 'en'));
  }, [setLang]);

  const t = useMemo(
    () => ({ ...translations[lang], app: APP_TRANSLATIONS[lang] }),
    [lang]
  );

  useEffect(() => {
    document.documentElement.lang = lang;
    document.title =
      lang === 'hi'
        ? 'वैधानिक मापन अनुपालन प्रणाली | उपभोक्ता मामले विभाग'
        : 'Legal Metrology Compliance System | Department of Consumer Affairs';
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, toggleLang, t }), [lang, toggleLang, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
